package data_test

import (
	"github.com/bazelbuild/rules_go/tests/core/go_proto_compiler/foo"
	"testing"
)

func TestData(t *testing.T) {
	// Foo_greeting2 is a string generated by the data plugin
	// using the content of the data.conf file as value.
	if foo.Foo_greeting2 != "Hallo Welt!\n" {
		t.Logf(`Got : "%s"`, foo.Foo_greeting2)
		t.Logf(`Want: "Hallo Welt!\n"`)
		t.FailNow()
	}
}
