package executable_runfiles_test

import (
	"github.com/bazelbuild/rules_go/tests/core/go_proto_compiler/foo"
	"testing"
)

func TestExecutableRunfiles(t *testing.T) {
	// Foo_greeting is a string generated by the executable_runfiles plugin
	// using the content of the executable_runfiles.conf file as value.
	if foo.Foo_greeting != "Hello World!" {
		t.FailNow()
	}
}
