package(default_visibility = ["//examples/monobuild/cmd:__pkg__"])

load("//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "lib1.go",
    ],
    import_path = "full/import/path/to/lib1",
)
